version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: container_macro_score
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - cache

  cache:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
