version: '1.0'

services:
  app:
    build: ./app
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=root
      - MONGO_HOST=db
      - REDIS_URL=redis://cache:6379/0
    volumes:
      - .:/code

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodb_data:/data/db

  cache:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
