name: Deploy Backend to Render

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./Backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/macro-score:latest

      - name: Install Core Utilities
        run: |
          echo "Installing core utilities..."
          sudo apt-get update
          sudo apt-get install -y coreutils
          echo "Core utilities installation completed."
        shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  
      - name: Install and configure Homebrew
        run: |
          echo "Installing Homebrew..."
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "PATH=/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/opt/deno/bin:$PATH" >> $GITHUB_ENV
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          echo "Homebrew installation completed."
        shell: /usr/bin/bash -e {0}
  
      - name: Install Deno
        run: |
          echo "Installing Deno..."
          brew install deno
          echo "Deno installed at: $(which deno)"
          deno --version
          echo "Deno installation completed."
        shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}

      - name: Debugging PATH and utilities
        run: |
          echo "Debugging PATH and installed utilities..."
          echo "Current PATH: $PATH"
          which curl || echo "curl not found"
          which deno || echo "deno not found"
          which brew || echo "brew not found"
          brew --version || echo "brew --version command failed"
          deno --version || echo "deno --version command failed"
          echo "Debugging completed."
        shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
        env:
          PATH: /home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/opt/deno/bin:$PATH
  
      - name: Tap Render CLI repository
        run: |
          echo "Tapping Render CLI repository..."
          brew tap render-oss/render
          echo "Render CLI repository tapped."
        shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  
      - name: Install Render CLI
        run: |
          echo "Installing Render CLI..."
          brew install render
          echo "Render CLI installation completed."
        shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
        env:
          PATH: /home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/opt/deno/bin:$PATH
  
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ALGORITHM: ${{ secrets.ALGORITHM }}
          ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
          REFRESH_TOKEN_EXPIRE_MINUTES: ${{ secrets.REFRESH_TOKEN_EXPIRE_MINUTES }}
        run: |
          render deploy --service MacroScore --env docker --repo https://github.com/Yanguas01/MacroScore_Replica --branch main
